import strutils,strformat,pegs

var sOut = """
-- DON'T EDIT THIS FILE
-- This file is auto generated by "nim makeIconFontTblDef.nims"
"""

sOut.add "\nrequire'IconsFontAwesome6'\n\n"
sOut.add "global iconFontTbl: []cstring = {\n"
for line in readfile("../utils/fonticon/IconsFontAwesome6.nim").split('\n'):
  let name = line.strip.split('*')[0]
  if name =~ peg"'ICON_FA_'":
    sOut.add fmt"{name} .. "" {name}"" ," & "\n"

sOut.add "}"

writefile("iconFontTblDef.nelua",sOut)
